In [1]:
%matplotlib widget
import matplotlib.pyplot as plt

In [2]:
from cn_plot_style import cn_plot_style as cnps                                                    
import numpy as np                                                              
from matplotlib import pyplot as plt   

In [3]:
preamble = '/home/tobias/ZMBP/talks posters presentations writings/thesis/misc/preamble.tex'
def read_preamble(filename):
    with open(filename) as file:
        preamble = ''
        for line in file:
            if line.startswith(r'\usepackage'):
                preamble = ''.join((preamble, line.strip(), ','))
    return preamble
prmbl = read_preamble(preamble)

FileNotFoundError: [Errno 2] No such file or directory: '/home/tobias/ZMBP/talks posters presentations writings/thesis/misc/preamble.tex'

In [4]:
# Create data to be plotted                                                     
x = np.linspace(0, 50, 2000)                                                    
data = np.sin(x)                                                                
noisy_data = data + np.random.randn(2000) * 5                                   
                                                                                
# Plot data for a 'notebook' with dark background on one axis, and cycle        
# through colors:                                                               
with cnps.cn_plot(context='notebook', dark=True, preamble=prmbl) as cnp:
    fig, ax = plt.subplots()              
    ax2 = cnps.second_ax(fig=fig, link_ax=ax, enable_spines=True) 

    lns1 = ax.plot(x, noisy_data, label='data')
    lns2 = ax2.plot(x, data, label='fit')

    cnps.legend(lns1, lns2)
    #plt.legend()

    #ax.set_title('Example fit of a sinus')
    ax.set_xlabel('Time')      
    ax.set_ylabel(r'Amplitude \uppi')
    #ax2.set_ylabel('Amplitude')



NameError: name 'prmbl' is not defined

In [5]:
"""
===========
Broken Axis
===========
Broken axis example, where the y-axis will have a portion cut out.
"""
import matplotlib.pyplot as plt
import numpy as np


# 30 points between [0, 0.2) originally made using np.random.rand(30)*.2
pts = np.array([
    0.015, 0.166, 0.133, 0.159, 0.041, 0.024, 0.195, 0.039, 0.161, 0.018,
    0.143, 0.056, 0.125, 0.096, 0.094, 0.051, 0.043, 0.021, 0.138, 0.075,
    0.109, 0.195, 0.050, 0.074, 0.079, 0.155, 0.020, 0.010, 0.061, 0.008])

# Now let's make two outlier points which are far away from everything.
pts[[3, 14]] += .8

# If we were to simply plot pts, we'd lose most of the interesting
# details due to the outliers. So let's 'break' or 'cut-out' the y-axis
# into two portions - use the top (ax) for the outliers, and the bottom
# (ax2) for the details of the majority of our data
f, (ax, ax2) = plt.subplots(2, 1, sharex=True)

# plot the same data on both axes
ax.plot(pts)
ax2.plot(pts)

# zoom-in / limit the view to different portions of the data
ax.set_ylim(.78, 1.)  # outliers only
ax2.set_ylim(0, .22)  # most of the data

# hide the spines between ax and ax2
ax.spines['bottom'].set_visible(False)
ax2.spines['top'].set_visible(False)
ax.xaxis.tick_top()
ax.tick_params(labeltop=False)  # don't put tick labels at the top
ax2.xaxis.tick_bottom()

# This looks pretty good, and was fairly painless, but you can get that
# cut-out diagonal lines look with just a bit more work. The important
# thing to know here is that in axes coordinates, which are always
# between 0-1, spine endpoints are at these locations (0,0), (0,1),
# (1,0), and (1,1).  Thus, we just need to put the diagonals in the
# appropriate corners of each of our axes, and so long as we use the
# right transform and disable clipping.

d = .015  # how big to make the diagonal lines in axes coordinates
# arguments to pass to plot, just so we don't keep repeating them
kwargs = dict(transform=ax.transAxes, color='k', clip_on=False)
ax.plot((-d, +d), (-d, +d), **kwargs)        # top-left diagonal
ax.plot((1 - d, 1 + d), (-d, +d), **kwargs)  # top-right diagonal

kwargs.update(transform=ax2.transAxes)  # switch to the bottom axes
ax2.plot((-d, +d), (1 - d, 1 + d), **kwargs)  # bottom-left diagonal
ax2.plot((1 - d, 1 + d), (1 - d, 1 + d), **kwargs)  # bottom-right diagonal

# What's cool about this is that now if we vary the distance between
# ax and ax2 via f.subplots_adjust(hspace=...) or plt.subplot_tool(),
# the diagonal lines will move accordingly, and stay right at the tips
# of the spines they are 'breaking'

#plt.show()

FigureCanvasNbAgg()

In [6]:
from brokenaxes.brokenaxes import BrokenAxes as brokenaxes
brokenaxes??

Init signature: brokenaxes(xlims=None, ylims=None, d=0.015, tilt=45, subplot_spec=None, fig=None, despine=True, *args, **kwargs)
Source:        
class BrokenAxes:
    def __init__(self, xlims=None, ylims=None, d=.015, tilt=45,
                 subplot_spec=None, fig=None, despine=True,
                 *args, **kwargs):
        """Creates a grid of axes that act like a single broken axes

        Parameters
        ----------
        xlims, ylims: (optional) None or tuple of tuples, len 2
            Define the ranges over which to plot. If `None`, the axis is left
            unsplit.
        d: (optional) double
            Length of diagonal split mark used to indicate broken axes
        tilt: (optional) double
            Angle of diagonal split mark
        subplot_spec: (optional) None or Gridspec.subplot_spec
            Defines a subplot
        fig: (optional) None or Figure
            If no figure is defined, `plt.gcf()` is used
        despine: (optional) bool
            

In [8]:
from brokenaxes.brokenaxes import BrokenAxes as brokenaxes
import numpy as np

fig = plt.figure(figsize=(5,2))
bax = brokenaxes(fig=fig, xlims=((0, .1), (.4, .7)), ylims=((-1, .7), (.79, 1)), hspace=.05)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(10 * x), label='sin')
bax.plot(x, np.cos(10 * x), label='cos')
bax.legend(loc=3)
bax.set_xlabel('time')
bax.set_ylabel('value')

FigureCanvasNbAgg()

Text(0,0.5,'value')

In [9]:
from matplotlib.gridspec import GridSpec
import numpy as np

fig = plt.figure()
sps1, sps2 = GridSpec(2,1)

bax = brokenaxes(xlims=((.1, .3),(.7, .8)), subplot_spec=sps1)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(x*30), ls=':', color='m')

x = np.random.poisson(3, 1000)
bax = brokenaxes(xlims=((0, 2.5), (3, 6)), subplot_spec=sps2)
bax.hist(x, histtype='bar')

FigureCanvasNbAgg()

[(array([ 50., 135., 212., 242., 171., 100.,  45.,  30.,  12.,   3.]),
  array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]),
  <a list of 10 Patch objects>),
 (array([ 50., 135., 212., 242., 171., 100.,  45.,  30.,  12.,   3.]),
  array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]),
  <a list of 10 Patch objects>)]